# Generated by Django 5.0.6 on 2024-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_data',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=100)),
                ('admin_password', models.CharField(max_length=20)),
                ('admin_gender', models.CharField(max_length=10)),
                ('admin_role', models.CharField(max_length=20)),
                ('admin_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_password', models.CharField(max_length=20)),
                ('customer_gender', models.CharField(max_length=10)),
                ('customer_role', models.CharField(max_length=20)),
                ('customer_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
