# Generated by Django 5.0.6 on 2024-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_data',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_category', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('prdouct_image', models.ImageField(blank=True, null=True, upload_to='productimage/')),
            ],
        ),
    ]
