# Generated by Django 5.0.6 on 2024-06-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_data',
            old_name='prdouct_image',
            new_name='product_image',
        ),
    ]
