# Generated by Django 5.0.6 on 2024-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='customer_address',
            field=models.TextField(null=True),
        ),
    ]
